name: apocalypse
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - python=3.7
  - seaborn
  - jupyterlab
  - pip
    - git+https://github.com/exoplanet-dev/exoplanet.git#egg=exoplanet
  - numpy
  - pymc3
